name: Deploy on VPS

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y nodejs npm

      - name: Build
        run: |
          cd /home/ubuntu/projects/Portfolio
          npm install
          npm run build

      - name: Restart app
        run: |
          cd /home/ubuntu/projects/Portfolio
          pm2 delete portfolio || true
          pm2 start npm --name portfolio -- run start
#          pm2 restart portfolio || pm2 start npm --name portfolio -- run start

