name: Test SSH

on:
  push:
    branches:
      - main

jobs:
  test-ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Debug VPS_KEY
        run: echo "${{ secrets.VPS_KEY }}" | head -n 50

      - name: Write private key
        run: |
          mkdir -p ~/.ssh
          printf "%s" "${{ secrets.VPS_KEY }}" > ~/.ssh/gh-actions-key
          chmod 600 ~/.ssh/gh-actions-key
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Try SSH
        run: |
          ssh -vvv -i ~/.ssh/gh-actions-key -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} 'echo OK'
