name: Deploy na VPS

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Instalacja zależności (np. Node.js)
        run: |
          sudo apt update
          sudo apt install -y nodejs npm

      - name: Build (jeśli masz build)
        run: |
          npm install
          npm run build

      - name: Restart aplikacji
        run: |
          pm2 restart my-app || echo "Nie znaleziono aplikacji"
